name: Build and Push Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - auto-cpu
          # - invoke
          # - comfy
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
      - run: docker compose --profile ${{ matrix.profile }} push
